name: Boss

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  boss:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install Hero
        run: yarn && yarn build
        working-directory: ./hero
        env:
          BROWSERS_DIR: /tmp/chromes

      - name: Install Databox
        run: yarn && yarn build
        working-directory: ./databox

      - name: Yarn build
        run: yarn && yarn build

      - name: Zip Chromes
        run: cd /tmp/chromes && tar -czf chromes.tar.gz ./*

      - name: Copy Chrome
        run: mkdir ./build/apps/boss/chromes && cp /tmp/chromes/chromes.tar.gz ./build/apps/boss/chromes/

      - name: Build Boss
        run: yarn dist
        working-directory: ./apps/boss
        env:
          USE_HARD_LINKS: false
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Boss
        if: ${{ github.ref != 'refs/heads/main' || failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: boss-${{ matrix.os }}
          path: |
            ./build/apps/boss/dist/*.zip
            ./build/apps/boss/dist/*.AppImage
            ./build/apps/boss/dist/*.dmg
            ./build/apps/boss/dist/*.exe
          retention-days: 1
