name: ChromeAlive!

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  chromealive:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install Hero
        run: yarn && yarn build
        working-directory: ./hero
        env:
          HERO_SKIP_CHROME_DOWNLOAD: 1

      - name: Install Databox
        run: yarn && yarn build
        working-directory: ./databox

      - name: Yarn build
        run: yarn && yarn build
        env:
          ULX_CHROMEALIVE_SKIP_BINARY_DOWNLOAD: 1

      - name: Build Chromealive
        run: yarn dist
        working-directory: ./apps/chromealive

      - name: Upload to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          assets=()
          for asset in ./build/apps/chromealive/dist/assets/*; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release edit "${assets[@]}" -m "" "$tag_name"

      - name: Upload Chromealive
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: 'chromealive'
          path: ./build/apps/chromealive/dist/assets/*
          retention-days: 1
