name: Desktop

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  app:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Add msbuild to PATH
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.1

      - name: Yarn build
        run: yarn && yarn build:dist

      - run: mkdir ~/.private_keys && echo "$APPLE_NOTARIZE_KEY" > ~/.private_keys/AuthKey_5VH6PQ3585.p8
        if: ${{ matrix.os == 'macos-latest' }}
        shell: bash
        env:
          APPLE_NOTARIZE_KEY: ${{secrets.APPLE_NOTARIZE_KEY}}

      - name: Build Desktop
        run: yarn dist
        working-directory: ./desktop/main
        env:
          NODE_ENV: production
          USE_HARD_LINKS: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Upload App
        if: startsWith(github.ref, 'refs/tags/v') == false || failure()
        uses: actions/upload-artifact@v3
        with:
          name: desktop-${{ matrix.os }}
          path: |
            ./build/desktop/main/dist/*.AppImage
            ./build/desktop/main/dist/*.dmg
            ./build/desktop/main/dist/*.exe
          retention-days: 1
