name: Desktop

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  app:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install pcap
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install -y libpcap-dev

      - name: Clone unblocked
        run: git clone --recurse-submodules -j8 https://github.com/ulixee/unblocked.git
        working-directory: ..

      - name: Install unblocked
        run: yarn build:all
        working-directory: ../unblocked

      - name: Chocolatey Install Action
        if: ${{ matrix.os == 'windows-latest' }}
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install python2 visualcpp-build-tools -y

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Install Hero
        run: yarn && yarn build
        working-directory: ./hero

      - name: Yarn build
        run: yarn && yarn build

      - run: mkdir ~/.private_keys && echo "$APPLE_NOTARIZE_KEY" > ~/.private_keys/AuthKey_5VH6PQ3585.p8
        if: ${{ matrix.os == 'macos-latest' }}
        shell: bash
        env:
          APPLE_NOTARIZE_KEY: ${{secrets.APPLE_NOTARIZE_KEY}}

      - name: Build Desktop
        run: yarn dist
        working-directory: ./apps/desktop
        env:
          NODE_ENV: production
          USE_HARD_LINKS: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

      - name: Upload App
        if: ${{ github.ref != 'refs/heads/main' || failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: desktop-${{ matrix.os }}
          path: |
            ./build/apps/desktop/dist/*.AppImage
            ./build/apps/desktop/dist/*.dmg
            ./build/apps/desktop/dist/*.exe
          retention-days: 1
