name: Build a Docker

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: Build latest docker release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Read version
        shell: bash
        working_directory: server/main
        run: export VERSION=$(node -p "require('package.json').version")
      - name: Login to Container Repository
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Using $(docker -v)"
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Build Image
        shell: bash
        working_directory: server/tools/docker
        env:
          GITHUB_URL: https://github.com/${{ github.repository }}
          BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
          ADD_CHROME_VERSION: '@ulixee/chrome-104-0'
        run: |
          docker build \
            --progress tty \
            --cache-from ghcr.io/ulixee:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            \
            --build-arg BUILD_DATE=${BUILD_DATE} \
            --build-arg GITHUB_SHA=${GITHUB_SHA} \
            --build-arg ADD_TO_INSTALL="yarn add $ADD_CHROME_VERSION" \
            --build-arg VERSION=${VERSION} \
            \
            --tag ghcr.io/ulixee:v${VERSION} \
            --tag docker.io/ulixee:v${VERSION} \
            \
            --label org.label-schema.build-date=${BUILD_DATE} \
            --label org.label-schema.vcs-url=${GITHUB_URL} \
            --label org.label-schema.vcs-ref=${GITHUB_SHA} \
            \
            --label org.opencontainers.image.created=${BUILD_DATE} \
            --label org.opencontainers.image.source=${GITHUB_URL} \
            --label org.opencontainers.image.revision=${GITHUB_SHA} \
            .
      - name: Push Image to GHCR
        shell: bash
        working_directory: server/tools/docker
        run: docker push -a ghcr.io/ulixee

      - name: Push Image to Dockerhub
        if: ${{secrets.DOCKER_IO_TOKEN}}
        shell: bash
        working_directory: server/tools/docker
        env:
          DOCKER_IO_TOKEN: ${{ secrets.DOCKER_IO_TOKEN }}
        run: |
          echo "${DOCKER_IO_TOKEN}" | docker login docker.io -u "${{ github.actor }}" --password-stdin
          >&0 docker push -a docker.io/ulixee
