name: Check Docs Links

on:
  push:
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check README
        uses: becheran/mlc@v0.15.4
        with:
          args: ./README.md

      - name: Check Datastore Docs
        uses: becheran/mlc@v0.15.4
        with:
          args: ./datastore/docs

      - name: Check Cloud Docs
        uses: becheran/mlc@v0.15.4
        with:
          args: ./cloud/docs

