name: Check Docs Links

on:
  push:
  workflow_dispatch:

jobs:
  links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check README
        uses: becheran/mlc@v0.15.4
        with:
          args: ./README.md

      - name: Check Databox Docs
        uses: becheran/mlc@v0.15.4
        with:
          args: ./databox/docs

      - name: Check Miner Docs
        uses: becheran/mlc@v0.15.4
        with:
          args: ./miner/docs

