name: 'Publish a built Javascript Branch'

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Javascript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install pcap
        run: sudo apt-get install -y libpcap-dev

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Clone ulixee/shared
        run: git clone https://github.com/ulixee/shared.git
        working-directory: ..

      - name: Install ulixee/shared
        run: yarn && yarn build
        working-directory: ../shared

      - name: Clone ulixee/payments
        run: git clone https://github.com/ulixee/payments.git
        working-directory: ..

      - name: Install ulixee/payments
        run: yarn && yarn build
        working-directory: ../payments

      - name: Clone unblocked
        run: git clone --recurse-submodules -j8 https://github.com/ulixee/unblocked.git
        working-directory: ..

      - name: Install unblocked
        run: yarn build
        working-directory: ../unblocked

      - name: Install Hero
        run: yarn build
        working-directory: ./hero

      - name: Set timeout
        run: yarn config set network-timeout 1000000 -g

      - name: Build modules
        run: yarn && yarn build:dist

      - name: Publish branch
        run: |
          cd build-dist
          git config --global user.email "staff@ulixee.org"
          git config --global user.name "CI"
          git init -b main
          git add -A
          git commit -m 'Auto-build Javascript files'
          git push -f https://ulixee:${{ env.GH_TOKEN }}@github.com/ulixee/platform.git main:${{ github.ref_name }}-built-js
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
