name: Test Matrix

on:
  push:
    branches:
      - '*'
      - '!gh-pages'
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Test Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [14, 16]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Chocolatey Install Action
        if: ${{ matrix.os == 'windows-latest' }}
        uses: crazy-max/ghaction-chocolatey@v1.4.2
        with:
          args: install python2 visualcpp-build-tools -y

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        if: ${{ matrix.os == 'windows-latest' }}

      - name: (TEMP) Clone ulixee/commons
        run: git clone --recurse-submodules -j8 https://github.com/ulixee/commons.git
        working-directory: ..

      - name: (TEMP) Install ulixee/commons
        run: yarn && yarn build
        working-directory: ../commons

      - name: (TEMP) Clone ulixee/net
        run: git clone --recurse-submodules -j8 https://github.com/ulixee/net.git
        working-directory: ..

      - name: (TEMP) Install ulixee/net
        run: yarn && yarn build
        working-directory: ../net

      - name: (TEMP) Clone unblocked
        run: git clone --recurse-submodules -j8 https://github.com/unblockable/unblocked.git
        working-directory: ..

      - name: (TEMP) Install unblocked
        run: yarn build:all
        working-directory: ../unblocked

      - name: Install Hero
        run: yarn && yarn build
        working-directory: ./hero

      - name: Yarn build
        run: yarn && yarn build
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1

      - name: Linux - Apt Install Chrome(s)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: ./build
        run: sudo $(npx install-browser-deps)

      - name: Run Lint
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == 14 }}
        run: NODE_OPTIONS=--max-old-space-size=4096 yarn lint

      - name: Run tests
        run: yarn test --testTimeout=60000 --maxWorkers=2

      - name: 'Tar files'
        if: ${{ failure() }}
        run: tar -cvf test-dbs.tar build/.data-test

      - name: Upload Databases
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-dbs-${{matrix.os}}-${{ matrix.node-version }}
          path: test-dbs.tar
          retention-days: 1
