name: Test Matrix

on:
  push:
    branches:
      - '*'
      - '!gh-pages'
  workflow_dispatch:

jobs:
  lint-and-test:
    name: Test Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [14, 16]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Hero
        run: yarn && yarn build
        working-directory: ./hero

      - name: Install Databox
        run: yarn && yarn build
        working-directory: ./databox

      - name: Yarn build
        run: yarn && yarn build
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1

      - name: Linux - Apt Install Chrome(s)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: ./build
        run: sudo $(npx install-browser-deps)

      - name: Run  Lint
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node-version == 14 }}
        run: NODE_OPTIONS=--max-old-space-size=4096 yarn lint

      - name: Run tests
        run: yarn test:all --testTimeout=30000 --maxWorkers=2
        env:
          NODE_ENV: test
          HERO_DATA_DIR: .data

      - name: 'Tar files'
        if: ${{ failure() }}
        run: tar -cvf test-dbs.tar .data

      - name: Upload Databases
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-dbs-${{matrix.os}}-${{ matrix.node-version }}
          path: test-dbs.tar
          retention-days: 1
