name: Test Matrix

on:
  push:
    branches:
      - '*'
      - '!gh-pages'
  workflow_dispatch:

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Yarn install
        run: yarn && yarn build
        working-directory: ./hero
        env:
          HERO_SKIP_CHROME_DOWNLOAD: 1
          ULX_CHROMEALIVE_SKIP_BINARY_DOWNLOAD: 1

      - name: Yarn install
        run: yarn && yarn build
        working-directory: ./databox
        env:
          HERO_SKIP_CHROME_DOWNLOAD: 1
          ULX_CHROMEALIVE_SKIP_BINARY_DOWNLOAD: 1

      - name: Yarn build
        run: yarn && yarn build
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
          HERO_SKIP_CHROME_DOWNLOAD: 1
          ULX_CHROMEALIVE_SKIP_BINARY_DOWNLOAD: 1

      - name: Run  Lint
        run: NODE_OPTIONS=--max-old-space-size=4096 yarn lint

  test:
    name: Test Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    needs: lint
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [14, 16]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Yarn install
        run: yarn && yarn build
        working-directory: ./hero
        env:
          HERO_SKIP_CHROME_DOWNLOAD: 1
          ULX_CHROMEALIVE_SKIP_BINARY_DOWNLOAD: 1

      - name: Yarn install
        run: yarn && yarn build
        working-directory: ./databox
        env:
          HERO_SKIP_CHROME_DOWNLOAD: 1
          ULX_CHROMEALIVE_SKIP_BINARY_DOWNLOAD: 1

      - name: Yarn build
        run: yarn && yarn build
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
          HERO_SKIP_CHROME_DOWNLOAD: 1
          ULX_CHROMEALIVE_SKIP_BINARY_DOWNLOAD: 1

      - name: Linux - Apt Install Chrome(s)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: ./build
        run: sudo $(npx install-browser-deps)

      - name: Run tests
        run: yarn test:all
        env:
          NODE_ENV: test
          HERO_DATA_DIR: .data

      - name: 'Tar files'
        if: ${{ failure() }}
        run: tar -cvf test-dbs.tar ./build/.data

      - name: Upload Databases
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-dbs-${{matrix.os}}-${{ matrix.node-version }}
          path: test-dbs.tar
          retention-days: 1
