name: Release Test Matrix

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    name: Test Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [14, 16, 18]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Chocolatey Install Action
        if: ${{ matrix.os == 'windows-latest' }}
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install python2 visualcpp-build-tools -y

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Install Hero
        run: yarn && yarn build
        working-directory: ./hero

      - name: Yarn build
        run: yarn && yarn build
        env:
          ELECTRON_SKIP_BINARY_DOWNLOAD: 1

      - name: Linux - Apt Install Chrome(s)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        working-directory: ./build
        run: sudo $(npx install-browser-deps)

      - name: /etc/hosts
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }}
        run: |
          sudo echo "127.0.0.1 docs.datastoresrus.com" | sudo tee -a /etc/hosts
          sudo echo "127.0.0.1 bootup-datastore.com" | sudo tee -a /etc/hosts
        shell: bash

      - name: C:/Windows/System32/drivers/etc/hosts
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          echo "127.0.0.1 docs.datastoresrus.com" | tee -a C:/Windows/System32/drivers/etc/hosts
          echo "127.0.0.1 bootup-datastore.com" | tee -a C:/Windows/System32/drivers/etc/hosts
        shell: bash

      - name: Run tests
        run: yarn test --testTimeout=60000 --maxWorkers=2
        env:
          CI: true

      - name: 'Tar files'
        if: ${{ failure() }}
        run: tar -cvf test-dbs.tar build/.data-test

      - name: Upload Databases
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-dbs-${{matrix.os}}-${{ matrix.node-version }}
          path: test-dbs.tar
          retention-days: 1
