name: Website

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  website:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: yarn
        run: yarn install --network-timeout 1000000
        working-directory: ./website

      - name: Build Webite
        run: yarn build
        working-directory: ./website

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build-dist/website
          commit_message: '[skip ci] Updates'
